/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Comming soon...': '敬请期待...',
    'Crit DMG': '暴击伤害',
    'Crit Chance: +': '暴击率: +',
    'EXP Boost': '经验提升',
    'EXP Buff': '经验增益',
    'Upgrade': '升级',
    'Utility': '通用的',
    'Challenge': '挑战',
    'Loot': '战利品',
    'Shop': '商店',
    'Field': '田野',
    'Setting': '设置',
    'Click': '点击',
    'Export Game': '导出存档',
    'Click)': '点击)',
    'Dmg': '伤害',
    'DMG Boost': '伤害提升',
    'Total Play Time': '累计游戏时间',
    'Total Status': '总属性',
    'Unlock meta world': '解锁元世界',
    'Mastery': '精通',
    'Level': '等级',
    'Hit/s': '击中/秒',
    'token': '令牌',
    'Overall Boost': '整体提高',
    'Otherworldy': '异界',
    'Otherworldy chest': '异界宝箱',
    'Enter Code': '输入口令',
    'Damage Buff': '伤害增益',
    'Goblin Loot -': '哥布林战利品 -',
    'Artifact': '神器',
    'Artifact wont reset': '神器不会重置',
    'All)': '全部)',
    'xMax': 'x最大',
    'Timer)': '计时器)',
    'Click Buff': '点击增益',
    'Timer': '计时器',
    ' Chest': ' 宝箱',
    ' Click': ' 点击',
    ' Loot': ' 战利品',
    ' Mastery': ' 精通',
    ' Otherworldy': '超越',
    ' Token': ' 令牌',
    ' Stage': ' 阶段',
    ' Quest': ' 任务',
    'Tier': '层',
    'Iron sword +': '铁剑 +',
    'Spiked bat +': '尖刺蝙蝠 +',
    'Water bomb +': '水炸弹+',
    'Topaz Sword +': '黄玉剑+',
    'Snowball +': '雪球 +',
    'Sapphire Sword +': '蓝宝石剑+',
    'Rope +': '绳子 +',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'Comming Soon': '敬请期待',
    'Kor': '韩语',
    'Eng': '英文',
    'Cactus water bottle -': '仙人掌水瓶 -',
    'Bush water bottle -': '布什水瓶 -',
    'You got Cactus water bottle! (You Own': '你得到仙人掌水瓶!(你有',
    'Thorn arrow +': '刺箭 +',
    'Disable Low Detail Mod': '禁用低细节模式',
    'You got Shiny Goblin Loot! (You Own': '你得到了闪光哥布林战利品！（你有',
    'TP gain': 'TP 获得',
    'You got Goblin Loot! (You Own': '你得到了哥布林战利品！（你有',
    'Skill line 4, 5 (Not implemented yet': '技能线4、5（尚未实施',
    'The maximum level of the weapon is +999!': '武器的最高等级为+999！',
    'My Discord!': '我的Discord!',
    'Multi Layer Quest': '多层任务',
    'Rare-class sword chance': '稀有剑几率',
    'Start with +25 SP': '以+25 SP开始',
    'Rare-grade sword damage is low, but with experience bottle!': '稀有剑的伤害低，但是有经验瓶！',
    'None +': '无 +',
    'Mysterious Chest Chance': '神秘宝箱几率',
    'Mysterious Chest -': '神秘宝箱-',
    'Monster Weakness: +': '怪物弱点: +',
    'Monster EXP Buff': '怪物经验增益',
    'Monster kill stat +': '怪物杀死统计+',
    'Monster Weakness Cap': '怪物弱点上限',
    'Bonus Loot: +': '奖励战利品：+',
    'Boost amount of tokens gained based on Level': '根据等级提高获得的代币数量',
    'Boost EXP gain based on the Sum of all weapon Levels': '根据所有武器等级的总和提高经验值',
    'Break Weakness Cap': '打破弱点上限',
    'Click Bought Skill again to Refund': '再次单击“购买技能”以退款',
    'Join My Discord Server!': '加入我的Discord服务器!',
    'The amount of experience required is x3.2 each time the level goes up.!': '每次升级，所需经验值都 x3.2。',
    'You got Slime Loot! (You Own': '你得到了史莱姆战利品！ （你有',
    'You got Shiny Slime Loot! (You Own': '你得到了闪光史莱姆战利品！ （你有',
    'Additional damage based on level': '根据等级附加伤害',
    'Powerful monster appears (Loot': '强大的怪物出现（战利品',
    'Tokens can also be obtained by Auto Click': '也可以通过自动点击获得令牌',
    'Token click upgrade applies to automatic clicks, too': '令牌点击升级也适用于自动点击',
    'Token boost obtained with timer based on Level': '基于级别的计时器获得令牌提升',
    'Toggle display tickrate at Status': '切换属性显示的滴答声',
    'Exp boost based on Transcesion Point': '经验提升鲫鱼超越点',
    'Go to meta world!': '进入元世界！',
    'Make some Skill stronger': '使一些技能更强',
    'Enable Low Detail Mod': '启用低细节模式',
    'Dmg boost based on Otherworldy count': '根据异界计数增加伤害',
    'EXP Bottle -': '经验瓶 -',
    'Increase Max Level': '提高最大等级',
    'Inventory': '库存',
    'Lv.': '等级.',
    'Lv': '等级',
    'Import Game': '导入存档',
    'Skill Price -': '技能价格 -',
    'Slime Loot -': '史莱姆战利品 - ',
    'Token Shop': '令牌商店',
    'Low Detail Mod': '低细节模式',
    'Click bought auto to toggle': '点击购买自动切换',
    'Change Notation': '改变符号',
    'Chance to get double loot when defeating a monster': '有机会在打败怪物时获得双倍的战利品',
    'Chance to Discover Mysterious Chest': '发现神秘箱子的几率',
    'Chance to Discover Artifact': '发现藏物的几率',

    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "Expressionless Slime (hp: ": "面无表情的史莱姆 (生命值：",
    "Happy Slime (hp: ": "快乐史莱姆 (生命值：",
    "Cactus (hp: ": "仙人掌 (生命值：",
    "Slime (hp: ": "史莱姆 (生命值：",
    "Surprised Slime (hp: ": "惊奇的史莱姆 (生命值：",
    "Angry Slime (hp: ": "愤怒史莱姆 (生命值：",
    "Bat Goblin (hp: ": "蝙蝠哥布林 (生命值：",
    "Ranger Goblin (hp: ": "游侠哥布林 (生命值：",
    "Bomb Goblin (hp: ": "炸弹哥布林 (生命值：",
    "Thrower Goblin (hp: ": "投掷哥布林 (生命值：",
    "Warrior Goblin (hp: ": "战士哥布林 (生命值：",
    "Weapon ": "武器 ",
    "Auto": "自动",
    "Auto ": "自动",
    "Monster Kill Stat": "怪物击杀统计",
    "Tick rate: ": "Tick率:",
    "Token (": "令牌 (",
    "Token Boost (": "令牌提升 (",
    "Sword ": "剑 ",
    "Shiny ": "闪光 ",
    "Token Upgrade (": "令牌升级 (",
    "Reset Game (": "重置游戏 (",
    "Player Level (": "玩家等级 (",
    "Gel sword ": "凝胶剑",
    "Gel boomerang ": "凝胶回旋镖",
    "Go to other world (0 TP)!": "前往其他世界（0 TP）！",
    "Collect": "收集",
    "Monster EXP start at ": "怪物经验开始于",
    " Token (": " 令牌 (",
    "Dmg:": "伤害:",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "\n": "",
    " EXP (": " 经验 (",
    " Token (": " 令牌 (",
    " (": " (",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^([\d\.]+) \/([\d\.]+) K$/, //纯空格
    /^([\d\.]+) K\/([\d\.]+) K$/, //纯空格
    /^([\d\.]+) T\/([\d\.]+) T$/, //纯空格
    /^([\d\.]+) B\/([\d\.]+) B$/, //纯空格
    /^([\d\.]+) B\/([\d\.]+) T$/, //纯空格
    /^([\d\.]+) \/$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) SP$/, '$1 技能点'],
    [/^(\d+) TP$/, '$1 超越点'],
    [/^You Have (.+) Transcension Point$/, '你有 $1 超越点'],
    [/^You Have (.+) Skill Point$/, '你有 $1 技能点'],
    [/^You Have (.+) Tokens$/, '你有 $1 令牌'],
    [/^Reach Level (.+) to Open$/, '达到 $1 级即可开启'],
    [/^There are (.+) monsters, and (.+) bosses!$/, '这里有 $1 怪物,和 $2 Boss!'],
    [/^Monster Lv(.+) \((.+)\/$/, '怪物等级 $1 \($2\/'],
    [/^Buy \((.+)  Token$/, '购买 \($1 令牌'],
    [/^Buy \((.+) token$/, '购买 \($1 令牌'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^([\d\.]+) Token \($/, '$1 令牌 \('],
    [/^([\d\.]+) token \($/, '$1 令牌 \('],
    [/^([\d\.]+) K token \($/, '$1 K 令牌 \('],
    [/^([\d\.]+) token$/, '$1 令牌'],
    [/^([\d\.]+)  token \($/, '$1 令牌 \('],
    [/^([\d\.]+)  Token \($/, '$1 令牌 \('],
    [/^([\d\.]+)  hp$/, '$1 生命值'],
    [/^([\d\.]+) B hp$/, '$1 B 生命值'],
    [/^Arti (.+) is permanent$/, '艺术 $1 是永久性的'],
    [/^\- (.+)\/(.+) EXP \($/, '\- $1\/$2 经验 \('],
    [/^\- (.+) K\/(.+) K EXP \($/, '\- $1 K\/$2 K 经验 \('],
    [/^\- (.+) K\/(.+) M EXP \($/, '\- $1 K\/$2 M 经验 \('],
    [/^(\d+)\-(\d+) level up! \+(.+) ▶ \+$/, '$1\-$2 等级提高! \+$3 ▶ \+'],
    [/^Thorn arrow level up! \+(.+) ▶ \+$/, '刺箭等级提高! \+$1 ▶ \+'],
    [/^Spiked bat level up! \+(.+) ▶ \+$/, '尖刺蝙蝠等级提高! \+$1 ▶ \+'],
    [/^Iron sword level up! \+(.+) ▶ \+$/, '铁剑等级提高! \+$1 ▶ \+'],
    [/^(.+)Tick Rate: (.+) ms$/, 'Tick率: $2 毫秒'],
    [/^Buy \((.+) Token$/, '购买 \($1 令牌'],
    [/^level up! \+(\d+) ▶ \+$/, '升级了! \+$1 ▶ \+'],
    [/^(\d+)\-(\d+) \(hp\: ([\d\.]+) B\/([\d\.]+) T$/, '$1\-$2 \(生命值\:$3 B\/$4 T'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^You got (\d+)\-(\d+)! \(You Own$/, '你获得了 $1\-$2! \(你有'],
    [/^(\d+)\-(\d+) \(hp\: ([\d\.]+) T\/([\d\.]+) T$/, '$1\-$2 \(生命值\: $3 T\/$4 T'],

]);